"""cria tabelas de sacola e item_sacola

Revision ID: 7b57e6fcf566
Revises: a1a52c5fbbed
Create Date: 2026-09-20 14:18:47.924751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b57e6fcf566'
down_revision = 'a1a52c5fbbed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sacola',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.BigInteger(), nullable=False),
    sa.Column('restaurante_id', sa.BigInteger(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['restaurante_id'], ['restaurante.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sacola', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sacola_restaurante_id'), ['restaurante_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sacola_usuario_id'), ['usuario_id'], unique=True)

    op.create_table('item_sacola',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('sacola_id', sa.BigInteger(), nullable=False),
    sa.Column('produto_id', sa.BigInteger(), nullable=False),
    sa.Column('quantidade', sa.BigInteger(), nullable=False),
    sa.Column('observacao', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['produto_id'], ['produto.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sacola_id'], ['sacola.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('item_sacola', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_item_sacola_produto_id'), ['produto_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_item_sacola_sacola_id'), ['sacola_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item_sacola', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_item_sacola_sacola_id'))
        batch_op.drop_index(batch_op.f('ix_item_sacola_produto_id'))

    op.drop_table('item_sacola')
    with op.batch_alter_table('sacola', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sacola_usuario_id'))
        batch_op.drop_index(batch_op.f('ix_sacola_restaurante_id'))

    op.drop_table('sacola')
    # ### end Alembic commands ###
