"""estado inicial do banco

Revision ID: 7fbcad2a15fe
Revises: 
Create Date: 2026-09-08 19:58:13.770532

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7fbcad2a15fe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
        batch_op.alter_column('nome',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=254),
               existing_nullable=False)
        batch_op.drop_constraint(batch_op.f('usuarios_email_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_usuarios_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_usuarios_telefone'), ['telefone'], unique=False)
        batch_op.drop_column('data_criacao')
        batch_op.drop_column('senha_hash')
        batch_op.drop_column('provedor_auth')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('provedor_auth', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('senha_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('data_criacao', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.drop_index(batch_op.f('ix_usuarios_telefone'))
        batch_op.drop_index(batch_op.f('ix_usuarios_email'))
        batch_op.create_unique_constraint(batch_op.f('usuarios_email_key'), ['email'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('email',
               existing_type=sa.String(length=254),
               type_=sa.VARCHAR(length=150),
               existing_nullable=False)
        batch_op.alter_column('nome',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.drop_column('criado_em')

    # ### end Alembic commands ###
