"""criar todas as tabelas

Revision ID: a1a52c5fbbed
Revises: 
Create Date: 2026-09-20 12:38:23.279415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1a52c5fbbed'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('codigos_verificacao',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('destino', sa.String(length=150), nullable=False),
    sa.Column('canal', sa.String(length=20), nullable=False),
    sa.Column('codigo', sa.String(length=6), nullable=False),
    sa.Column('expira_em', sa.Float(), nullable=False),
    sa.Column('verificado', sa.Boolean(), nullable=False),
    sa.Column('verificado_expira_em', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('codigos_verificacao', schema=None) as batch_op:
        batch_op.create_index('idx_destino_canal_verificado', ['destino', 'canal', 'verificado'], unique=False)
        batch_op.create_index(batch_op.f('ix_codigos_verificacao_destino'), ['destino'], unique=False)

    op.create_table('ingrediente',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ingrediente', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ingrediente_nome'), ['nome'], unique=True)

    op.create_table('restaurante',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=False),
    sa.Column('categoria_principal', sa.String(length=50), nullable=False),
    sa.Column('taxa_entrega', sa.Float(), nullable=True),
    sa.Column('tempo_estimado', sa.String(length=20), nullable=True),
    sa.Column('logradouro', sa.String(length=254), nullable=False),
    sa.Column('numero', sa.String(length=10), nullable=False),
    sa.Column('complemento', sa.String(length=100), nullable=True),
    sa.Column('bairro', sa.String(length=50), nullable=False),
    sa.Column('cidade', sa.String(length=50), nullable=False),
    sa.Column('uf', sa.String(length=2), nullable=False),
    sa.Column('cep', sa.String(length=10), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('restaurante', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_restaurante_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_restaurante_telefone'), ['telefone'], unique=False)

    op.create_table('usuarios',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('documento', sa.String(length=20), nullable=True),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuarios_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_usuarios_telefone'), ['telefone'], unique=False)

    op.create_table('enderecos',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tipo_endereco', sa.String(length=30), nullable=False),
    sa.Column('logradouro', sa.String(length=100), nullable=False),
    sa.Column('numero', sa.String(length=10), nullable=False),
    sa.Column('complemento', sa.String(length=100), nullable=True),
    sa.Column('bairro', sa.String(length=50), nullable=False),
    sa.Column('cidade', sa.String(length=50), nullable=False),
    sa.Column('uf', sa.String(length=2), nullable=False),
    sa.Column('cep', sa.String(length=10), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('usuario_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('enderecos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_enderecos_usuario_id'), ['usuario_id'], unique=False)

    op.create_table('produto',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('restaurante_id', sa.BigInteger(), nullable=False),
    sa.Column('nome', sa.String(length=60), nullable=False),
    sa.Column('descricao', sa.String(length=8000), nullable=False),
    sa.Column('preco', sa.Float(), nullable=False),
    sa.Column('disponivel', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['restaurante_id'], ['restaurante.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('produto', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_produto_nome'), ['nome'], unique=False)
        batch_op.create_index(batch_op.f('ix_produto_restaurante_id'), ['restaurante_id'], unique=False)

    op.create_table('produto_ingrediente',
    sa.Column('produto_id', sa.BigInteger(), nullable=False),
    sa.Column('ingrediente_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['ingrediente_id'], ['ingrediente.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['produto_id'], ['produto.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('produto_id', 'ingrediente_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('produto_ingrediente')
    with op.batch_alter_table('produto', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_produto_restaurante_id'))
        batch_op.drop_index(batch_op.f('ix_produto_nome'))

    op.drop_table('produto')
    with op.batch_alter_table('enderecos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_enderecos_usuario_id'))

    op.drop_table('enderecos')
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuarios_telefone'))
        batch_op.drop_index(batch_op.f('ix_usuarios_email'))

    op.drop_table('usuarios')
    with op.batch_alter_table('restaurante', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_restaurante_telefone'))
        batch_op.drop_index(batch_op.f('ix_restaurante_email'))

    op.drop_table('restaurante')
    with op.batch_alter_table('ingrediente', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ingrediente_nome'))

    op.drop_table('ingrediente')
    with op.batch_alter_table('codigos_verificacao', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_codigos_verificacao_destino'))
        batch_op.drop_index('idx_destino_canal_verificado')

    op.drop_table('codigos_verificacao')
    # ### end Alembic commands ###
