"""adiciona email e campos ao restaurante

Revision ID: e37e2b325af4
Revises: 7fbcad2a15fe
Create Date: 2026-09-12 14:57:09.846619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e37e2b325af4'
down_revision = '7fbcad2a15fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restaurante',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=False),
    sa.Column('categoria_principal', sa.String(length=50), nullable=False),
    sa.Column('taxa_entrega', sa.Float(), nullable=True),
    sa.Column('tempo_estimado', sa.String(length=20), nullable=True),
    sa.Column('logradouro', sa.String(length=254), nullable=False),
    sa.Column('numero', sa.String(length=10), nullable=False),
    sa.Column('complemento', sa.String(length=100), nullable=True),
    sa.Column('bairro', sa.String(length=50), nullable=False),
    sa.Column('cidade', sa.String(length=50), nullable=False),
    sa.Column('uf', sa.String(length=2), nullable=False),
    sa.Column('cep', sa.String(length=10), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('restaurante', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_restaurante_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_restaurante_telefone'), ['telefone'], unique=False)

    with op.batch_alter_table('enderecos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_enderecos_parceiro_id'))
        batch_op.drop_constraint(batch_op.f('enderecos_parceiro_id_fkey'), type_='foreignkey')
        batch_op.drop_column('parceiro_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enderecos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parceiro_id', sa.BIGINT(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('enderecos_parceiro_id_fkey'), 'usuarios', ['parceiro_id'], ['id'])
        batch_op.create_index(batch_op.f('ix_enderecos_parceiro_id'), ['parceiro_id'], unique=False)

    with op.batch_alter_table('restaurante', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_restaurante_telefone'))
        batch_op.drop_index(batch_op.f('ix_restaurante_email'))

    op.drop_table('restaurante')
    # ### end Alembic commands ###
